services:
  ruwork_routing.i18n_router:
    class: Ruwork\RoutingBundle\Routing\I18nRouter
    parent: router.default
    calls:
      - [setRequestStack, ['@request_stack']]

  router: '@ruwork_routing.i18n_router'

  ruwork_routing.i18n_loader:
    class: Ruwork\RoutingBundle\Routing\I18nLoader
    arguments:
      - '@ruwork_routing.i18n_loader.inner'
      - []
      - ~
    decorates: routing.loader
