services:
  ruwork_routing.i18n_router:
    class: Ruwork\RoutingBundle\Routing\I18nRouter
    parent: router.default
    calls:
      - [setDefaultLocale, ["%locale%"]]
      - [setRequestStack, ["@request_stack"]]

  router: "@ruwork_routing.i18n_router"

  ruwork_routing.i18n_loader:
    class: Ruwork\RoutingBundle\Routing\I18nLoader
    arguments:
      - "@ruwork_routing.i18n_loader.inner"
    decorates: routing.loader

  ruwork_routing.template_loader:
    class: Ruwork\RoutingBundle\Routing\TemplateLoader
    arguments:
      - "@templating.name_parser"
      - "@file_locator"
    tags:
      - { name: routing.loader }
