language: php

php:
    - 7.1
    - 7.2

env:
    - SYMFONY_VERSION=~3.4.0
    - SYMFONY_VERSION=~4.0.0

install:
    - >
        sed -i.bac 's#"\(symfony/[[:alnum:]-]*\)": "[^"]*"#"\1": "'"${SYMFONY_VERSION}"'"#g' composer.json
    - composer install
